name = "koby-contact-form"
main = "contact-form-worker.js"
compatibility_date = "2024-01-01"
account_id = "4fcec980c07ca7ef02087d9e61f20e42"



[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true