name = "chadis-conversation"
main = "chadis-conversation-worker.js"
compatibility_date = "2024-10-15"
account_id = "4fcec980c07ca7ef02087d9e61f20e42"

[vars]
ELEVENLABS_API_KEY = "sk_f280dbfe3fdbbf0ef1c5f73a2cbafaba0f5c71999d99bb86"